### ISSUE TITLE
How to Batch download

### ISSUE THREAD

**Issue by seane4422** [lovasoa/dezoomify-rs#208] opened 2023-06-19 21:01 UTC
Hi I'm having an issue batch downloading, I was amazed to see the first result googling this was someone trying to downloading the exact same thing i am 'The book of kells' i'm on a mac here, im trying to get the full rez versions,  i tried the code you suggested in the original post and could not get it to work, any help appreciated, https://digitalcollections.tcd.ie/concern/works/hm50tr726

**Comment by lovasoa** [comment] 2023-06-23 14:45
Duplicate of #17

**Comment by lovasoa** [comment] 2023-06-23 14:45
I'm closing this to centralize discussion about batching in #17

**Closed by lovasoa** 2023-06-23 14:45 UTC
