### ISSUE TITLE
Laurenziana Medicia Library again!

### ISSUE THREAD

**Issue by CharlyAlonso** [lovasoa/dezoomify-rs#145] opened 2021-08-11 16:15 UTC
Hi how are things?
Sorry to bother again and, perhaps, with a topic already discussed. But, I'm going crazy and I can't find the key.
Is about:
http://mss.bmlonline.it/s.aspx?Id=AWODj-zNI1A4r7GxL9jf&c=Evangelia%20characteribus%20Syriacis%20exarata#/book
It is a manuscript from the Biblioteca Medicia Laurenziana
I have managed to put:
https://dezoomify.ophir.dev/#http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto01\.\P000046_01.56\pyr \ Plut._01.56_0016.tif / TileGroup0 / 2-0-0.jpg

at https://dezoomify.ophir.dev/ and I manage to download image 16 without major problems.
But of course, the problem is that I cannot build a script to download the 600 or so pages of the manuscript. I have to go one at a time!
Can you think of any way to do it?

In another vein there is a very good material in the Royal Botanical Garden of Spain, for example:

https://bibdigital.rjb.csic.es/viewer/9470/?offset=#page=1&viewer=picture&o=bookmark&n=0&q=

In this environment you can easily get a configuration file for the entire volume. In this case:

https://bibdigital.rjb.csic.es/api/viewer/lgiiif?url=/srv/www/limbgallery/medias/84/ac/0e/b1/84ac0eb1-35b9-4316-8c88-7d0055d5afda/

It would be great if your wonderful program dezoomify-rs supports this parameter and downloads all the pages individually.
It is simply a proposal.

Thank you very much for everything from Spain,
CaC

**Comment by lovasoa** [comment] 2021-08-11 16:45
Hello,
  You can use xargs to download multiple images at once. 
  See
 - https://github.com/lovasoa/dezoomify-rs#batch-mode
 - https://github.com/lovasoa/dezoomify-rs/issues/17

I'm closing this issue as a duplicate of #17

**Closed by lovasoa** 2021-08-11 16:45 UTC

**Comment by CharlyAlonso** [comment] 2021-08-11 17:11
> Hi how are things?
> Sorry to bother again and, perhaps, with a topic already discussed. But, I'm going crazy and I can't find the key.
> Is about:
> http://mss.bmlonline.it/s.aspx?Id=AWODj-zNI1A4r7GxL9jf&c=Evangelia%20characteribus%20Syriacis%20exarata#/book
> It is a manuscript from the Biblioteca Medicia Laurenziana
> I have managed to put:
> [https://dezoomify.ophir.dev/#http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto01\.\P000046_01.56\pyr](https://dezoomify.ophir.dev/#http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=%5C%5CTECA-NAS%5CTeca%5CPlutei%5CLotto01%5C.%5CP000046_01.56%5Cpyr) \ Plut._01.56_0016.tif / TileGroup0 / 2-0-0.jpg
> 
> at https://dezoomify.ophir.dev/ and I manage to download image 16 without major problems.
> But of course, the problem is that I cannot build a script to download the 600 or so pages of the manuscript. I have to go one at a time!
> Can you think of any way to do it?
> 
> In another vein there is a very good material in the Royal Botanical Garden of Spain, for example:
> 
> https://bibdigital.rjb.csic.es/viewer/9470/?offset=#page=1&viewer=picture&o=bookmark&n=0&q=
> 
> In this environment you can easily get a configuration file for the entire volume. In this case:
> 
> https://bibdigital.rjb.csic.es/api/viewer/lgiiif?url=/srv/www/limbgallery/medias/84/ac/0e/b1/84ac0eb1-35b9-4316-8c88-7d0055d5afda/
> 
> It would be great if your wonderful program dezoomify-rs supports this parameter and downloads all the pages individually.
> It is simply a proposal.
> 
> Thank you very much for everything from Spain,
> CaC

I have explained myself fatally, I have a painful English, I'm sorry!
I have solved the batch problem in windows with Aria2c.exe. It's going very well, really!
My problem is that if I put the URL http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto01\.\P000046_01.56\pyr \ Plut. _01.56_0016.tif / TileGroup0 / 2-0-0.jpg

by https://dezoomify.ophir.dev/

it works perfectly.
But, if I do it with dezoomify-rs.exe there is no way.

That's why I say that I have to enter one by one in https://dezoomify.ophir.dev/

Anyway, thank you very much.
All the best,
CaC

**Comment by lovasoa** [comment] 2021-08-11 17:34
You can extract informations from your json using jq : 

```
curl "https://bibdigital.rjb.csic.es/api/viewer/lgiiif?url=/srv/www/limbgallery/medias/84/ac/0e/b1/84ac0eb1-35b9-4316-8c88-7d0055d5afda/" --insecure | jq '.item.tiles[]["@id"]' -r
```

**Comment by CharlyAlonso** [comment] 2021-08-12 20:37
Sorry to bother again, really; but I'm going crazy !!!!

If I run:

dezoomify-rs.exe http://mss.bmlonline.it/fcgi-bin/iipsrv.fcgi?Zoomify=\\TECA-NAS\Teca\Plutei\Lotto01\.\P000046_01.56\pyr\Plut._01.56_0240 .tif / TileGroup1 / 5 - {{X}} - {{Y}}. jpg

I get this!!!!!!!

![dezoomified_0002](https://user-images.githubusercontent.com/66141658/129266257-7908c76a-be35-4792-8cc3-27557f7f5699.jpg)


I'm desperate!
CaC
