### ISSUE TITLE
Direct copy of Google Art URL can not be downloaded locally?

### ISSUE THREAD

**Issue by mrchen0606** [lovasoa/dezoomify-rs#41] opened 2020-05-11 12:48 UTC
Sorry, maybe the question I ’m asking is idiot, but I really do n’t know how to download Google Art pictures locally
https://artsandculture.google.com/asset/blessed-osanna-andreasi-unknown-artist-16th-century/xwENpFFD-ABMuw
![image](https://user-images.githubusercontent.com/65124511/81563387-c705a680-93c8-11ea-88bd-a622b2c773e1.png)

**Comment by lovasoa** [comment] 2020-05-11 12:55
Hi,
  I cannot reproduce this issue. This looks like a network issue on your side...

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/552629/81563924-424e6480-9397-11ea-9377-9319d86598c0.png">

  I'm marking this as needinfo, I'll reopen if we manage to reproduce.

**Closed by lovasoa** 2020-05-11 12:55 UTC

**Comment by lovasoa** [comment] 2020-05-11 12:59
![Blessed Osanna Andreasi - Unknown artist_ 16th century](https://user-images.githubusercontent.com/552629/81564419-010a8480-9398-11ea-9d1d-4a6b3c678b0f.jpg)

**Comment by mrchen0606** [comment] 2020-05-12 02:55
Sorry, it's really my network problem. I can't connect to the external network in my area, if there is a proxy option

**Comment by lovasoa** [comment] 2020-05-12 06:24
Yes, dezoomify-rs should follow your system's proxy settings
