### ISSUE TITLE
Mac OS - Bad CPU type in executable

### ISSUE THREAD

**Issue by qubed** [lovasoa/dezoomify-rs#257] opened 2024-09-03 13:40 UTC
![Screen Shot 2024-09-03 at 8 37 50 AM](https://github.com/user-attachments/assets/895b2914-6e65-4f49-ad4f-f219d82e16a8)

I am encountering a zsh: bad CPU Type in executable error when running the latest version of dezoomify-rs on my Mac OS Monterey 12.7.6.

I had been using the previous version of dezoomify without issue, however, it appears after updating I am unable to run dezoomify from the command line. Any advice to get this working?

**Comment by lovasoa** [comment] 2024-09-03 14:02
Hello!
I'm closing this as a duplicate of https://github.com/lovasoa/dezoomify-rs/issues/250

**Closed** 2024-09-03 14:02 UTC
