### ISSUE TITLE
IIIF re-tiler - tiles missing

### ISSUE THREAD

**Issue by Linden6** [lovasoa/dezoomify-rs#70] opened 2020-09-07 20:27 UTC
I've noticed that the experimental IIIF re-tiler is dropping tiles on a fairly regular basis.

As an example, I've downloaded two images from the National Gallery of Art (NGA) at different zoom levels, and then generated images showing the tiles returned for different zoom levels.  Dropped tiles are always edge tiles.  They can occur on any edge - not just on the right and bottom side as in the examples below - and run the whole length of that edge.

Although I'm using examples from the NGA, the issue doesn't appear to be site-specific, or relate to the format of the original image.

I've be grateful if you could take a look at why this might be happening.  I'm hoping that the problem isn't too difficult to remedy.  (I did have a quick look at the source code, but I'm afraid that - due to my lack of familiarity with Rust - I'd need to invest a considerable amount of time and effort to get my head around it well enough to pinpoint the problem.)

Many thanks.
-----
[NGA Durer image](https://www.nga.gov/collection/art-object-page.53157.html)
`dezoomify-rs --compression 10  https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/5/3/1/5/7/53157-primary-0-nativeres.ptif durer.iiif`

Zoom level 3:
![tiles](https://user-images.githubusercontent.com/43049925/92414533-92261800-f14c-11ea-9715-65098b5826d6.png)

Zoom level 4:
![tiles](https://user-images.githubusercontent.com/43049925/92410614-977b6680-f13c-11ea-86a1-9dbd13eb2f02.png)

Zoom level 5 (no tiles missing):
![tiles](https://user-images.githubusercontent.com/43049925/92410864-7cf5bd00-f13d-11ea-811e-f379855b8284.png)

[NGA Corot image](https://www.nga.gov/collection/art-object-page.88615.html)
`dezoomify-rs --compression 10  https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/8/8/6/1/5/88615-primary-0-nativeres.ptif corot.iiif`

Zoom level 3 (no tiles at all produced):
![tiles](https://user-images.githubusercontent.com/43049925/92414981-c13d8900-f14e-11ea-9001-bab34fe65705.png)

Zoom level 4:
![tiles](https://user-images.githubusercontent.com/43049925/92415031-f21dbe00-f14e-11ea-8dda-6e90982335ac.png)

Zoom level 5:
![tiles](https://user-images.githubusercontent.com/43049925/92415071-24c7b680-f14f-11ea-939f-59953574365f.png)

Zoom level 6:
![tiles](https://user-images.githubusercontent.com/43049925/92415107-550f5500-f14f-11ea-906b-1a9c084d6525.png)

Zoom level 7:
![tiles](https://user-images.githubusercontent.com/43049925/92415193-b9321900-f14f-11ea-8e4e-825da7bb87e8.png)

**Comment by lovasoa** [comment] 2020-09-07 21:20
Hello,
  I'm glad to see the retiler being used. It's a bit of code that is a little complex as you noticed, but the images you generated are great, they'll help me pin point the problem. If you want to help, you can try to reproduce the error in the form of a test function, in the same format as the `test_retiler` function in `src/encoder/retiler.rs`.

**Comment by lovasoa** [comment] 2020-09-07 21:30
The retiler works in the following way : 
a retiler represents an image at a certain zoom level. It had a child that represents the image at the next zoom level (where the image is smaller). The retiler receives tiles from the original image. The received tiles can have any size, so they can cover partially or entirely any number of tiles in the target image. It computes the list of tiles covered by the current image, and pastes the correct resized and cropped source tile into a temporary target tile in the user's temporary folder. When a target tile has been entirely covered by source tiles, it is encoded to jpeg and saved to the target folder. 

There is currently no code for handling partially covered tiles at the end of the process. Any target tile that will not have been entirely covered by source tiles will never be converted to jpeg and saved in the target image, and it will not even be removed from the temporary folder. This is something that needs fixing, and may or may not be the cause of the bug described here.

**Comment by Linden6** [comment] 2020-09-07 22:05
I had noticed that my /tmp directory was filling up with dezoomify BMP's!

I've just cleared it and run this command again:
`dezoomify-rs --compression 10  https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/5/3/1/5/7/53157-primary-0-nativeres.ptif durer-zl4.iiif`

The generated image above for Durer zoom level 4 shows 512 tiles missing for y > 1024, and my /tmp directory contains:
dezoomify_32300_level_1_position_1024x0.bmp
dezoomify_32300_level_1_position_1024x512.bmp
dezoomify_32300_level_1_position_1024x1024.bmp
dezoomify_32300_level_1_position_1024x1536.bmp

It would appear, therefore, that for some reason the 512 tiles output for y > 1024 aren't registering as completely covered and so not getting converted to JPG's and saved.  However, the 1024 child tiles, and their 2048 children, are fine.

The missing tiles are causing the right edge of the image (below) to be blurred as presumably the OpenSeaDragon viewer is using the child tiles to back generate images for the missing tiles.
![Grimshot 2020-09-07 22-51-10](https://user-images.githubusercontent.com/43049925/92418118-c81fc800-f15d-11ea-8d83-465dadf35d56.jpg)

As the retiler has all the source material to completely cover the tiles to be output it appears that the next step is to ascertain why:
a) the output tiles are not completely tiled, or
b) if they are, why this is no being detected.

Thanks!

**Comment by Linden6** [comment] 2020-09-07 23:03
This is a jpg image of the Durer drawing (zoom level 4) downloaded via dezoomify-rs:
![durer-zl4](https://user-images.githubusercontent.com/43049925/92419204-ec7ea300-f163-11ea-8bb1-201ed5357a27.jpg)

If you look at this closely it has a 1px black border running down the right-hand side.

This is the side where the 512 tiles are missing:
![tiles](https://user-images.githubusercontent.com/43049925/92419480-b510f600-f165-11ea-850e-2c0357e3e817.png)

This is a jpg image of the Corot  painting (zoom level 4) downloaded via dezoomify-rs:
![corot-zl4](https://user-images.githubusercontent.com/43049925/92419283-82b2c900-f164-11ea-9c12-1656b3a5d221.jpg)

If you look closely it has a 1px black border running down the right-hand side and along the bottom.

These are the sides where the 512 tiles are missing:
![tiles](https://user-images.githubusercontent.com/43049925/92419572-497b5880-f166-11ea-900a-25529bac0925.png)

I would hazard a guess that this is more than mere coincidence.

**Comment by Linden6** [comment] 2020-09-07 23:39
This correlation holds true for the other zoom levels for the Durer and Corot images.

The size of the Durer drawing full-size is 2595 x 4000 px, as can be found here:
[https://media.nga.gov/iiif/public/objects/5/3/1/5/7/53157-primary-0-nativeres.ptif/info.json](https://media.nga.gov/iiif/public/objects/5/3/1/5/7/53157-primary-0-nativeres.ptif/info.json)

At the largest zoom level (5) no tiles are lost, and the resultant image when pieced together is 2595 x 4000 px.

At zoom level 4 the resultant image, when pieced together is 1298 x 2000 px.

The width of zoom level 4 is half that of zoom level 5: 2595px / 2 = 1297.5px.  If the result had been rounded down to 1297px - rather than rounded up to 1298px - then then there would be no black edge, and I believe no missing tiles!

**Comment by lovasoa** [comment] 2020-09-08 09:42
I implemented the required logic to avoid discarding partially downloaded tiles in a578d6436de274c150456974c025a449c369944b. You'll be able to test it with the latest [pre-release](https://github.com/lovasoa/dezoomify-rs/releases) build when github finishes compiling it. Please tell me if this fixes your issue.

Additionally, before closing this issue, I'd like to fully understand where these missing pixels come from. It may be a bug in the dezoomer.

**Comment by Linden6** [comment] 2020-09-08 10:23
Many thanks.  I've just run the pre-release build on Durer zoom level 4:

Original build:
![tiles](https://user-images.githubusercontent.com/43049925/92463332-92152f00-f1c3-11ea-82d8-65e4f8cf9209.png)

Latest pre-release build:
![tiles](https://user-images.githubusercontent.com/43049925/92463422-b4a74800-f1c3-11ea-9e17-47f38980492f.png)

And also for Corot zoom level 6:

Original build:
![tiles](https://user-images.githubusercontent.com/43049925/92463648-fd5f0100-f1c3-11ea-85ef-f6ff177b153d.png)

Latest pre-release build:
![tiles](https://user-images.githubusercontent.com/43049925/92463831-3f884280-f1c4-11ea-8952-4987792024d4.png)

And, so some improvement - at least all the highest zoom level tiles are now present.

In response to your desire 'to fully understand where these missing pixels come from', I don't think it's so much that pixels are missing, but that the tile canvases that pixels are being copied across to are in some cases - due to a rounding error (?) - oversized by 1 pixel along their width or height, or both, and so the pixels can never completely cover them.

**Comment by Linden6** [comment] 2020-09-08 10:40
That the latest pre-release build is only saving partially filled tiles for the level where there is no scaling is confirmed by the warning messages - in this case for Corot zoom level 6:

> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=1024 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=2048 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=5120 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=1536 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=1536 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=4096 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=0 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=4608 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=512 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=3072 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=2560 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=1024 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=152 y=512 at zoom level 1 and position x=5632 y=3072 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=512 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=2560 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=3584 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=2048 y=3584 was not fully covered by source tiles. It misses 512 pixels.
> [2020-09-08T10:33:03Z WARN  dezoomify_rs::encoder::retiler] The target tile of size x=512 y=13 at zoom level 1 and position x=0 y=3584 was not fully covered by source tiles. It misses 512 pixels.
>

**Comment by lovasoa** [comment] 2020-09-08 13:31
I had forgotten to finalize inferior levels recursively. It's fixed.

**Comment by Linden6** [comment] 2020-09-08 14:33
That's wonderful - no tiles being dropped now!

As always, thanks for your rapid response.

**Closed** 2020-09-10 10:00 UTC
Labels: bug

**Comment by Linden6** [comment] 2020-09-10 14:49
Thanks for the detective work.  I've tried the build, and it's now working as it should - no black lines, no warning messages, just pixel perfection!
