### ISSUE TITLE
Download multiple images at once

### ISSUE THREAD

**Issue by mpostument** [lovasoa/dezoomify-rs#231] opened 2024-02-27 13:33 UTC
Hello, is there a way for me to give a list of files to download (for example in a file). I have multiple links which need to be downloaded

**Comment by lovasoa** [comment] 2024-02-27 17:46
Hello and welcome to dezoomify !

I'll close this as a duplicate of https://github.com/lovasoa/dezoomify-rs/issues/17

Contributions welcome !

**Closed by lovasoa** 2024-02-27 17:46 UTC
