### ISSUE TITLE
Batch mode for windows

### ISSUE THREAD

**Issue by ngoncom** [lovasoa/dezoomify-rs#163] opened 2022-02-17 19:40 UTC
Hi,

I've read docs and know that I can using Batch Mode, but this code is written for Linux;

`xargs -d '\n' -n 1 ./dezoomify-rs < ./urls.txt`

Can you share the code for Windows? I want download all link inside "urls.txt" with "zoom levels" = 6

Thank you so much!

**Comment by CharlyAlonso** [comment] 2022-02-18 11:57
Hi how are things?
I usually generate .bat files and put line by line each of the downloads:

dezoomify-rs.exe -r 3 -l "xxxxx.json" 001.png

And so, line by line.

I use Notepad++ as an editor. It's wonderful!

Greetings

**Comment by ngoncom** [comment] 2022-02-19 08:05
@CharlyAlonso: It works!

But could you help me set parameter for "zoom levels" = 6, because "-l" is for largest image.

Stupid me, thank you for help.

**Comment by CharlyAlonso** [comment] 2022-02-19 09:31
![image](https://user-images.githubusercontent.com/66141658/154795249-2e8d66f8-d2d7-4417-a1ef-7cf597e0c7e4.png)

**Comment by CharlyAlonso** [comment] 2022-02-19 09:33
Hi,

If you publish the URLs, I'll personalize them for you.

Greetings,

**Comment by ngoncom** [comment] 2022-02-19 21:53
Hi,

I've tested on this link:

`https://artsandculture.google.com/asset/the-last-supper-attributed-to-giampietrino-and-giovanni-antonio-boltraffio/gAEISwj5Pus85w`

And now I know the relationship between width + height vs "zoom levels":

<img width="661" alt="2022-02-20_044119" src="https://user-images.githubusercontent.com/8530544/154820093-6fd4b2d9-5ac6-46ac-afe5-dbdad2d9f378.png">

It seem:
- Level 1: max width & height = 1000px
- Level 2: max width & height = 1500px
- Level 3: max width & height = 2500px
- Level 4: max width & height = 5000px
- Level 5: max width & height = 10000px
- Level 6: max width & height = 20000px
- Level 7: max width & height = 40000px
- Level 1: max width & height = 80000px

So for "zoom levels" = 4, I set:

```
dezoomify-rs.exe -r 3 -w 5000 -h 5000 "https://artsandculture.google.com/asset/the-last-supper-attributed-to-giampietrino-and-giovanni-antonio-boltraffio/gAEISwj5Pus85w" 1.jpg
dezoomify-rs.exe -r 3 -w 5000 -h 5000 "https://artsandculture.google.com/asset/the-virgin-nursing-the-child-with-the-infant-st-john-the-baptist-in-adoration/FAGiql9BkkRN8A" 2.jpg
```

It works well, thank you so much!

**Comment by CharlyAlonso** [comment] 2022-02-27 09:06
Please, do you close the thread?

Thank you and regards,

**Comment by zern** [comment] 2022-05-25 08:23
Share the bat script I use

@echo off
```
setlocal enabledelayedexpansion
set /a a=1
set /p downdir=Download folder: 
if "%downdir%"=="" set downdir="download"
if not exist %downdir% md %downdir%
for /f "delims=" %%i in (urls.txt) do (
dezoomify-rs -l --accept-invalid-certs -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36" %%i %downdir%/!a!.jpg
set /a a+=1
timeout /t 0
) 
pause
```

**Comment by lovasoa** [comment] 2023-06-23 14:46
I'm closing this to centralize discussion about batching in #17 

Duplicate of #17

**Closed by lovasoa** 2023-06-23 14:46 UTC
