### ISSUE TITLE
dezoomify-rs uses artsandculture.google.com addresses with special characters and does not work.

### ISSUE THREAD

**Issue by rokili** [lovasoa/dezoomify-rs#177] opened 2022-07-14 01:53 UTC
https://artsandculture.google.com/asset/der-ungl%C3%A4ubige-thomas-michelangelo-merisi-named-caravaggio/OAEjjQkNdRL9sg

https://artsandculture.google.com/asset/der-ungläubige-thomas-michelangelo-merisi-named-caravaggio/OAEjjQkNdRL9sg

Is this address unresolvable because it contains special character? What can you do?

**Comment by lovasoa** [comment] 2022-07-14 12:11
duplicate of #178

**Closed by lovasoa** 2022-07-14 12:11 UTC
